### ISSUE TITLE
NPM RUN is showing errors , i am unable to run it on local server

### ISSUE THREAD

**Issue by prabii** [egovernments/DIGIT-OSS#76]
C:\Users\codep\Downloads\DIGIT-OSS-master\DIGIT-OSS-master\frontend\mono-ui\web\rainmaker\node_modules\node-sass-chokidar\node_modules\node-sass\lib\binding.js:13
      throw new Error(errors.unsupportedEnvironment());
      ^

Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (108)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.14.1
    at module.exports (C:\Users\codep\Downloads\DIGIT-OSS-master\DIGIT-OSS-master\frontend\mono-ui\web\rainmaker\node_modules\node-sass-chokidar\node_modules\node-sass\lib\binding.js:13:13)
    at Object.<anonymous> (C:\Users\codep\Downloads\DIGIT-OSS-master\DIGIT-OSS-master\frontend\mono-ui\web\rainmaker\node_modules\node-sass-chokidar\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (C:\Users\codep\Downloads\DIGIT-OSS-master\DIGIT-OSS-master\frontend\mono-ui\web\rainmaker\node_modules\node-sass-chokidar\bin\node-sass-chokidar:18:9)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
C:\Users\codep\Downloads\DIGIT-OSS-master\DIGIT-OSS-master\frontend\mono-ui\web\rainmaker\node_modules\node-sass-chokidar\node_modules\node-sass\lib\binding.js:13
      throw new Error(errors.unsupportedEnvironment());
      ^

**Comment by jagankumar-egov** [comment]
@prabii  while running frontend/mono-ui 
The node version should be 12, so try switching to 12 using the node version manager(nvm),
also if you get any issue with node-sass try adding this line in package.json 
https://github.com/egovernments/DIGIT-OSS/blob/de0977bffc0e3796f6a0647c18e097f8d313a6a3/frontend/mono-ui/web/rainmaker/package.json#L99

If the issue doesn't get resolved try following steps
1. node version should be 12
2. In the following directory,
   web/rainmaker/ 
   execute this command  ```
yarn run clean
```  
3. then run ```
yarn run install
```  
4. Once installation is done, run ```
yarn run go
```  
5. once the run go command runs successfully, for the citizen interface run  ```
yarn run dev:citizen
```  and  for employee interface run  ```
yarn run dev:employee
```
